# Generated by Django 3.1.3 on 2020-11-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='url',
            field=models.URLField(null=True, verbose_name='URL of picture for the planet'),
        ),
        migrations.AddField(
            model_name='star',
            name='url',
            field=models.URLField(null=True, verbose_name='URL of picture for the planet'),
        ),
    ]
